### ISSUE TITLE
Importing excalibur-tiled in Electron

### ISSUE THREAD

**Issue by LePhil** [excaliburjs/excalibur-tiled#8]
As mentioned in https://github.com/excaliburjs/example-electron/issues/3, I'm not sure how to import excalibur-tiled in the Electron example.

TS won't let me use import * as ex.Extensions from "../bower_components/excalibur-tiled/dist/excalibur-tiled"; which seemed like the obvious approach. Importing it as an arbitrary Module (e.g. just Extensions) it of course doesn't work either.

**Comment by kamranayub** [comment]
There's a couple issues. First one is that the plugin has to be updated to
reference latest Excalibur. Second, the plugin isn't developed as a module
so you can't import it. Instead, just reference the script in the page.

For typescript, even when you do that there will still be an issue with the
namespacing. So the new version of the plugin drops the ex.Extension
namespace.

The new plugin is ready but not merged, it's in a branch in the
repository... We just have to release it, but you can use the JS and .d.ts
files from it, I think.

**Comment by kamranayub** [comment]
OK, I just updated it--try referencing the excalibur-tiled.js from your page.

You may need to modify the tsconfig.json to add a reference to the declarations for excalibur-tiled, since you can't import it as a module...

```
{
  "compilerOptions": {
  },
  "include": ["**/*.ts"],
  "files": ["bower_components/excalibur-tiled/dist/excalibur-tiled.d.ts"]
}
```

Something like that...

**Comment by LePhil** [comment]
Thanks for the answer! Unfortunately, and I hate to continue to bother you about it, something's not working.
So to make sure I didn't mess anything up, here's what I did:

1. clone excaliburjs/example-electron
2. npm install
3. npm start (works! yay for the greeter :+1: )
4. bower install excalibur-tiled
5. include the script in the page:
```
	<body>
		<script src="node_modules/excalibur/dist/excalibur.js"></script>
		<script src="bower_components/excalibur-tiled/dist/excalibur-tiled.js"></script>		
		<script>require('./game/index')</script>
	</body>
```

This throws the following error inside of Electron:
```
Uncaught ReferenceError: ex is not defined
    at Extensions.Tiled.Extensions.Tiled (excalibur-tiled.js:123)
```
I'm especially confused about having 2 versions of excalibur now, one via npm and one via bower. Is this correct or can one be removed?

**Comment by kamranayub** [comment]
Interesting! I think two versions are okay since you're including one...
But I suppose TS will be unhappy if you deleted the Bower version. You can
safely ignore it though, it doesn't have to be in your app--its just for
compile time.

I am not sure off the top of my head why it thinks ex isn't defined...
You're including it in the page, clearly. The test works too with it
included so that's weird.

Can you set a breakpoint at all in the Chrome debugger in Electron to
figure out what might be happening? Maybe to inspect when excalibur gets
defined and why it's loading out of order or something...

**Comment by kamranayub** [comment]
Oh duh! You can't use excalibur-tiled in a module loading environment alongside Excalibur, because it has to require excalibur to work and it assumes the browser variable exists. You can workaround it like this:

```
<script src="node_modules/excalibur/dist/excalibur.js"></script>
<script>window.ex = require('excalibur')</script>
<script src="bower_components/excalibur-tiled/dist/excalibur-tiled.js"></script>

<script>require('./game/index')</script>
```

Additionally, I released a patch for the TypeScript declarations so make sure you pull that, the compiler was complaining about a missing reference but I fixed that.

**Comment by LePhil** [comment]
Ah! Very cool, thanks. Didn't get to it anymore (dayjob etc) but I hope I have time to try it out tonight 👍

**Comment by LePhil** [comment]
Awesome, just tried it and it works! Might open an issue tomorrow because I think the spacing is not considered yet, but really cool to see a background map :+1: Thanks!
